export const MAX_STATUS_AGE_SECONDS = 290;
export const NEXT_PUBLIC_USER_AUTOREFRESH_SECONDS = 120;
export const TWITCH_USER_FIELDS = [
  'twitchId',
  'name',
  'displayName',
  'isLive',
  'lastOnline',
  'latestStreamTitle',
  'latestStreamStartedAt',
  'latestStreamViewers',
  'description',
  'type',
  'broadcasterType',
  'profilePictureUrl',
  'creationDate',
  'views',
  'country',
];

export const STATUS_UPDATE_FIELDS = [
  'isLive',
  'latestStreamTitle',
  'latestStreamStartedAt',
  'latestStreamViewers',
  'lastOnline',
];

/* cspell:disable */
export const DEFAULT_USERNAMES = [
  'CodingGarden',
  'GhostlyTuna',
  'clarkio',
  'KlassyKat',
  'Instafluff',
  'teej_dv',
  'theprimeagen',
  'cmgriffing',
  'trash_dev',
  'lizziepikachu',
  'ljtechdotca',
  'jlengstorf',
  'isaiahbydayah',
  'thedabolical',
  'learnwithleon',
  'thepracticaldev',
  'colbyfayock',
  'KidQueb',
  'mitchsworkshop',
  'designcourse',
  'wingmattdev',
  'TheAltF4Stream',
  'baldbeardedbuilder',
  'coderushed',
  'ched_dev',
  'VapeJuiceJordan',
  'robinmalfait',
  'mewtru',
  'ThePracticalDev',
  'bashbunni',
  'juiceboxhero',
  'jamiepine',
  'midudev',
  'splashley',
  'whitep4nth3r',
  '5t3phdev',
  'Aautophytes',
  'Simpathey',
  'phunkren',
  'mastermndio',
  'bradgarropy',
  'MelkeyDev',
  'jamesqquick',
  'cassidoo',
  'hswolff11',
  'florinpop17',
  'anthonywritescode',
  'beginbot',
  'erikdotdev',
  'snowxcones',
  'codephobia',
  'its_jay_phillz',
  'girlwithbox',
  'better_dev',
  'chris__sev',
  'portexe',
  'sxywu',
  'jacklynbiggin',
];
/* cspell:enable */
